version: '2'
services:
  zookeeper:
    image: zookeeper:3.5.5
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:5.4.1
    links:
      - zookeeper:zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  influx:
    image: influxdb:1.8-alpine
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influx